import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRefreshTokens1770973952141 implements MigrationInterface {
    name = 'AddRefreshTokens1770973952141'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_organizations"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_projects_organizations"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_work_sessions_organizations"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_work_sessions_users"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_work_sessions_projects"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "FK_daily_summaries_organizations"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "FK_daily_summaries_users"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_alerts_organizations"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_alerts_users"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_project_members_projects"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_project_members_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_org_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_id_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_work_sessions_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_daily_summaries_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_daily_summaries_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_activity_logs_session_ts"`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "projectId" uuid, "task" character varying, "description" character varying, "startTime" TIMESTAMP NOT NULL DEFAULT now(), "endTime" TIMESTAMP, "duration" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'running', "date" date NOT NULL DEFAULT ('now'::text)::date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD "activeSeconds" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD "idleSeconds" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD "lastActivityTimestamp" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD "isManual" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum" RENAME TO "user_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'manager', 'employee')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'employee'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_b5b6bbcd8846e78a24799d3f9c" ON "users" ("id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ddfb7904324cdba38d3c73de93" ON "users" ("organizationId", "email") `);
        await queryRunner.query(`CREATE INDEX "IDX_31f626808f3d0419937d2ceb65" ON "projects" ("organizationId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_84e011c678066c93b26c9d66bb" ON "work_sessions" ("organizationId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf6f156dfa4fa77e38db8269e3" ON "work_sessions" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f019938c72f2c4cd7f1ac2b3da" ON "daily_summaries" ("organizationId", "date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cb8fe5816add82bbcd9b3ab8fb" ON "daily_summaries" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_78cfa74165526191e28f4780b7" ON "alerts" ("userId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0baa098e21cd431976906c0c5" ON "alerts" ("organizationId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_953042fac6bfeae43f03901865" ON "activity_logs" ("sessionId", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_d19892d8f03928e5bfc7313780" ON "project_members" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_08d1346ff91abba68e5a637cfd" ON "project_members" ("userId") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_eec93fd979bdcf5a0141da324d6" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_d0e4b9129617a166a308b098ef6" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_7f1bcfe98595e0a130117224ddf" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_a7a790065ee6b574355dc15f61d" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_e6f6e60b98634422e89fb44e174" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "FK_3d1912f0050c5d2e48256044074" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "FK_1e32abf6645290616cbad2b5f52" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_5259a93699bf6b47307fbb2f04e" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_f2678f7b11e5128abbbc4511906" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_97f652d54fa17db1d697aea9247" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_597e6df96098895bf19d4b5ea45" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_67d411510fb2cb28df0463850d6" FOREIGN KEY ("sessionId") REFERENCES "work_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_d19892d8f03928e5bfc7313780c" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_08d1346ff91abba68e5a637cfdb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_08d1346ff91abba68e5a637cfdb"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_d19892d8f03928e5bfc7313780c"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_67d411510fb2cb28df0463850d6"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_597e6df96098895bf19d4b5ea45"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_97f652d54fa17db1d697aea9247"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_f2678f7b11e5128abbbc4511906"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_5259a93699bf6b47307fbb2f04e"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "FK_1e32abf6645290616cbad2b5f52"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "FK_3d1912f0050c5d2e48256044074"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_e6f6e60b98634422e89fb44e174"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_a7a790065ee6b574355dc15f61d"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_7f1bcfe98595e0a130117224ddf"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_d0e4b9129617a166a308b098ef6"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_eec93fd979bdcf5a0141da324d6"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08d1346ff91abba68e5a637cfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d19892d8f03928e5bfc7313780"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_953042fac6bfeae43f03901865"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0baa098e21cd431976906c0c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78cfa74165526191e28f4780b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb8fe5816add82bbcd9b3ab8fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f019938c72f2c4cd7f1ac2b3da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf6f156dfa4fa77e38db8269e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84e011c678066c93b26c9d66bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31f626808f3d0419937d2ceb65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddfb7904324cdba38d3c73de93"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5b6bbcd8846e78a24799d3f9c"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum_old" AS ENUM('admin', 'manager', 'employee')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_enum_old" USING "role"::"text"::"public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'employee'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum_old" RENAME TO "user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP COLUMN "isManual"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP COLUMN "lastActivityTimestamp"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP COLUMN "idleSeconds"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP COLUMN "activeSeconds"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`CREATE INDEX "IDX_activity_logs_session_ts" ON "activity_logs" ("sessionId", "timestamp") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_daily_summaries_user_date" ON "daily_summaries" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_daily_summaries_user_date" ON "daily_summaries" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_work_sessions_user_date" ON "work_sessions" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_id_status" ON "users" ("id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_users_org_email" ON "users" ("organizationId", "email") `);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_project_members_users" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_project_members_projects" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_alerts_users" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_alerts_organizations" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "FK_daily_summaries_users" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "FK_daily_summaries_organizations" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_work_sessions_projects" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_work_sessions_users" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_work_sessions_organizations" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_projects_organizations" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_organizations" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
